/** Mirror keys in root `codes.yaml` (SoT for httpStatus/message). */
const CODES = {
  SUCCESS: "SUCCESS",
  CREATED: "CREATED",
  INVALID_PARAM: "INVALID_PARAM",
  INVALID_JSON_BODY: "INVALID_JSON_BODY",
  INVALID_HEADER: "INVALID_HEADER",
  MISSING_CONTENT_TYPE: "MISSING_CONTENT_TYPE",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  STAFF_AUTH_REVOKE_PENDING: "STAFF_AUTH_REVOKE_PENDING",
  GATEWAY_SECRET_REJECTED: "GATEWAY_SECRET_REJECTED",
  MISSING_GATEWAY_USER_CONTEXT: "MISSING_GATEWAY_USER_CONTEXT",
  INVALID_USER_CONTEXT: "INVALID_USER_CONTEXT",
  PRECONDITION_REQUIRED: "PRECONDITION_REQUIRED",
  VERSION_CONFLICT: "VERSION_CONFLICT",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  DUPLICATE: "DUPLICATE",
  NO_MATCHING_API_PATH: "NO_MATCHING_API_PATH",
  DATASTORE_CREDENTIAL_REJECTED: "DATASTORE_CREDENTIAL_REJECTED",
};

export default CODES;
