name: Local
variables:
  - name: baseUrl
    value: http://127.0.0.1:{{port}}
  - name: port
    value: "3001"
  - name: ou_id
    value: 6a190d6c1fee03c383137249
  - name: branch_id
    value: 6a190d6c1fee03c38313724a
  - name: user_id
    value: 6a153e4c84136d940330991e
  - name: username
    value: branch_admin
  - name: password
    value: "1234"
  - name: access_token
    value: eyJhbGciOiJSUzI1NiIsImtpZCI6ImRlZmF1bHQifQ.eyJyb2xlIjoiYWRtaW4iLCJvdV9pZCI6IjZhMTkwZDZjMWZlZTAzYzM4MzEzNzI0OSIsImJyYW5jaF9pZCI6IjZhMTkwZDZjMWZlZTAzYzM4MzEzNzI0YSIsInRva2VuX2dlbiI6MCwic3ViIjoiNmExNTNlNGM4NDEzNmQ5NDAzMzA5OTFlIiwiaWF0IjoxNzgwMDI4OTM0LCJleHAiOjE3ODAwMjk4MzQsImlzcyI6Imh0dHBzOi8vYXV0aC5leGFtcGxlLmludmFsaWQiLCJhdWQiOiJnYXRld2F5In0.rY0BY82G0WDsccbw6NTLxsPGuf8n0pUg82trkx1c9DC5smccxDQv_4B8VWd53W_KCtiFefZn43qUtv37wgkKCZwe-6F4qY1BzlRN9658iB8r-uUL-tHZ5TAKL-zMlRWjlmUzBuENmJz2i6LRo8Ffe1jDbQlbm5KrwyVltUHhPWaOzFvjo69Dhtjgb-HmKomiC3lQ0BEEeZ5k6tAYbmuWZ6esUMDTn2BDpWzOKbO1x71efMy-xIE7ZjrwS0_ps2xnhQW3xbQpaJzf_EDj2MaxNwzKarTadlyc_nZcKlEaM9XgBeCu8RQXL4kYPYhQCj9vvDjV35q9CfbyKimvJZ1GYg
  - name: refresh_token
    value: YlyghIof6t_PdMvKouQ39ZndE5YjF9zXUYdvUwrVE-8
  - name: admin_test_menu_key
    value: sit:bruno:test
  - name: menu_upd_date
    value: ""
  - name: admin_test_role
    value: branch_admin
