/** Mirror keys in root `codes.yaml` (SoT for httpStatus/message). */
const CODES = {
  SUCCESS: "SUCCESS",
  CREATED: "CREATED",
  INVALID_PARAM: "INVALID_PARAM",
  INVALID_HEADER: "INVALID_HEADER",
  GATEWAY_SECRET_REJECTED: "GATEWAY_SECRET_REJECTED",
  MISSING_GATEWAY_USER_CONTEXT: "MISSING_GATEWAY_USER_CONTEXT",
  INVALID_USER_CONTEXT: "INVALID_USER_CONTEXT",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  DUPLICATE: "DUPLICATE",
  VERSION_CONFLICT: "VERSION_CONFLICT",
  PRECONDITION_REQUIRED: "PRECONDITION_REQUIRED",
  NO_MATCHING_API_PATH: "NO_MATCHING_API_PATH",
  INTERNAL_ERROR: "INTERNAL_ERROR",
};

export default CODES;
